#ifndef GAMESTATETYPE_H
#define GAMESTATETYPE_H

enum class GameStateType {
    CHOOSE_CHARACTER,
    COUNTING_POINT,
    FINISHED,
    GAME_OVER,
    GO_NEXT_MAP,
    IRIS_OUT,
    PLAYING,
    SETTING,
    TIME_UP,
    TITLE_SCREEN,
    CHOOSE_CUSTOMIZED_MAP,
    TEST_MAP,
    CUSTOM_MAP,
    NONE
};

#endif